
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GTEQ = 42;
  public static final int CHAR = 19;
  public static final int LTEQ = 43;
  public static final int EQUALS = 41;
  public static final int COMMENT = 3;
  public static final int MILSEC = 22;
  public static final int PLUSOP = 35;
  public static final int SEC = 23;
  public static final int LPAREN = 4;
  public static final int SEMI = 31;
  public static final int RPAREN = 5;
  public static final int EPSILON = 30;
  public static final int AND = 28;
  public static final int LTHAN = 40;
  public static final int NUMTYPE = 48;
  public static final int OR = 29;
  public static final int COMMA = 2;
  public static final int LSQBRACK = 27;
  public static final int LOOP = 13;
  public static final int MIN = 24;
  public static final int ASSIGN = 8;
  public static final int IF = 9;
  public static final int STRTYPE = 49;
  public static final int DOT = 33;
  public static final int WAIT = 45;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int PRINTLINE = 21;
  public static final int error = 1;
  public static final int NEGATION = 15;
  public static final int LCURLY = 6;
  public static final int NUMBER = 14;
  public static final int OBJFUNCID = 34;
  public static final int RCURLY = 7;
  public static final int TIMES = 16;
  public static final int BOOLTYPE = 51;
  public static final int GTHAN = 39;
  public static final int ELSE = 10;
  public static final int WHILE = 11;
  public static final int DIVOP = 36;
  public static final int HOUR = 25;
  public static final int RSQBRACK = 26;
  public static final int STRING = 17;
  public static final int CHARTYPE = 50;
  public static final int TIMESOP = 38;
  public static final int SUBOP = 37;
  public static final int BUTTON = 46;
  public static final int LED = 47;
  public static final int PRINT = 20;
  public static final int DO = 12;
  public static final int NOTEQ = 44;
  public static final int IDENTIFIER = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "COMMENT",
  "LPAREN",
  "RPAREN",
  "LCURLY",
  "RCURLY",
  "ASSIGN",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "LOOP",
  "NUMBER",
  "NEGATION",
  "TIMES",
  "STRING",
  "BOOLEAN",
  "CHAR",
  "PRINT",
  "PRINTLINE",
  "MILSEC",
  "SEC",
  "MIN",
  "HOUR",
  "RSQBRACK",
  "LSQBRACK",
  "AND",
  "OR",
  "EPSILON",
  "SEMI",
  "IDENTIFIER",
  "DOT",
  "OBJFUNCID",
  "PLUSOP",
  "DIVOP",
  "SUBOP",
  "TIMESOP",
  "GTHAN",
  "LTHAN",
  "EQUALS",
  "GTEQ",
  "LTEQ",
  "NOTEQ",
  "WAIT",
  "BUTTON",
  "LED",
  "NUMTYPE",
  "STRTYPE",
  "CHARTYPE",
  "BOOLTYPE"
  };
}

