
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVIDE = 44;
  public static final int WHEN = 24;
  public static final int CHAR = 4;
  public static final int EQUALS = 48;
  public static final int MILSEC = 11;
  public static final int CASE = 58;
  public static final int SEC = 12;
  public static final int TIME = 26;
  public static final int GREATER = 51;
  public static final int LPAREN = 32;
  public static final int INT = 17;
  public static final int PRINTLN = 18;
  public static final int LESS = 50;
  public static final int MINUS = 42;
  public static final int WRITE = 39;
  public static final int RPAREN = 33;
  public static final int AND = 46;
  public static final int NOT = 45;
  public static final int SEMICOLON = 36;
  public static final int OR = 47;
  public static final int COMMA = 37;
  public static final int BOOL = 6;
  public static final int LSQBRACK = 34;
  public static final int PLUS = 41;
  public static final int LOOP = 23;
  public static final int ASSIGN = 54;
  public static final int LESSEQ = 52;
  public static final int MIN = 13;
  public static final int IF = 19;
  public static final int DOT = 38;
  public static final int ID = 27;
  public static final int WAIT = 57;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int TRUE = 2;
  public static final int error = 1;
  public static final int NEGATION = 7;
  public static final int LCURLY = 30;
  public static final int NUMBER = 28;
  public static final int BREAK = 55;
  public static final int VOID = 8;
  public static final int RCURLY = 31;
  public static final int INTLITERAL = 16;
  public static final int TIMES = 43;
  public static final int COLON = 56;
  public static final int ELSE = 20;
  public static final int READ = 40;
  public static final int NOTEQUALS = 49;
  public static final int WHILE = 22;
  public static final int DEFAULT = 59;
  public static final int HOUR = 14;
  public static final int RSQBRACK = 35;
  public static final int GREATEREQ = 53;
  public static final int STRING = 5;
  public static final int STRINGLITERAL = 29;
  public static final int FALSE = 3;
  public static final int BUTTON = 9;
  public static final int LED = 10;
  public static final int PRINT = 15;
  public static final int DO = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUE",
  "FALSE",
  "CHAR",
  "STRING",
  "BOOL",
  "NEGATION",
  "VOID",
  "BUTTON",
  "LED",
  "MILSEC",
  "SEC",
  "MIN",
  "HOUR",
  "PRINT",
  "INTLITERAL",
  "INT",
  "PRINTLN",
  "IF",
  "ELSE",
  "DO",
  "WHILE",
  "LOOP",
  "WHEN",
  "RETURN",
  "TIME",
  "ID",
  "NUMBER",
  "STRINGLITERAL",
  "LCURLY",
  "RCURLY",
  "LPAREN",
  "RPAREN",
  "LSQBRACK",
  "RSQBRACK",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "WRITE",
  "READ",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "NOT",
  "AND",
  "OR",
  "EQUALS",
  "NOTEQUALS",
  "LESS",
  "GREATER",
  "LESSEQ",
  "GREATEREQ",
  "ASSIGN",
  "BREAK",
  "COLON",
  "WAIT",
  "CASE",
  "DEFAULT"
  };
}

